/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.harrih.view;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bttngitar = new javax.swing.JButton();
        bttnbass = new javax.swing.JButton();
        bttndrum = new javax.swing.JButton();
        bttnkeyboard = new javax.swing.JButton();
        bttnsaxophone = new javax.swing.JButton();
        bttnprofil = new javax.swing.JButton();
        bttnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(194, 133, 56));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BERANDA");

        bttngitar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttngitar.setText("SEJARAH ALAT MUSIK GITAR");
        bttngitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttngitarActionPerformed(evt);
            }
        });

        bttnbass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttnbass.setText("SEJARAH ALAT MUSIK BASS");
        bttnbass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnbassActionPerformed(evt);
            }
        });

        bttndrum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttndrum.setText("SEJARAH ALAT MUSIK DRUM");
        bttndrum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttndrumActionPerformed(evt);
            }
        });

        bttnkeyboard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttnkeyboard.setText("SEJARAH ALAT MUSIK KEYBOARD");
        bttnkeyboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnkeyboardActionPerformed(evt);
            }
        });

        bttnsaxophone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttnsaxophone.setText("SEJARAH ALAT MUSIK SAXOPHONE");
        bttnsaxophone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnsaxophoneActionPerformed(evt);
            }
        });

        bttnprofil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttnprofil.setText("PROFIL");
        bttnprofil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnprofilActionPerformed(evt);
            }
        });

        bttnlogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Shutdown-WF.png1.png")); // NOI18N
        bttnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(205, 205, 205))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttnprofil, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(bttnsaxophone, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(bttnkeyboard, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(bttndrum, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(bttnbass, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(bttngitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)))
                .addComponent(bttnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(bttngitar)
                        .addGap(18, 18, 18)
                        .addComponent(bttnbass)
                        .addGap(18, 18, 18)
                        .addComponent(bttndrum)
                        .addGap(18, 18, 18)
                        .addComponent(bttnkeyboard)
                        .addGap(18, 18, 18)
                        .addComponent(bttnsaxophone)
                        .addGap(18, 18, 18)
                        .addComponent(bttnprofil))
                    .addComponent(bttnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnlogoutActionPerformed
        // TODO add your handling code here:
        new MainView();
        setVisible(false);
        System.out.println("Anda Telah Logout");
        JOptionPane.showMessageDialog(null,"Anda Telah Logout","Logout",1);
    }//GEN-LAST:event_bttnlogoutActionPerformed

    private void bttngitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttngitarActionPerformed
        // TODO add your handling code here:
        new Guitar();
        dispose();
    }//GEN-LAST:event_bttngitarActionPerformed

    private void bttnbassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnbassActionPerformed
        // TODO add your handling code here:
        new Bass();
        dispose();
    }//GEN-LAST:event_bttnbassActionPerformed

    private void bttndrumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttndrumActionPerformed
        // TODO add your handling code here:
        new Drum();
        dispose();
    }//GEN-LAST:event_bttndrumActionPerformed

    private void bttnkeyboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnkeyboardActionPerformed
        // TODO add your handling code here:
        new Keyboard();
        dispose();
    }//GEN-LAST:event_bttnkeyboardActionPerformed

    private void bttnsaxophoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnsaxophoneActionPerformed
        // TODO add your handling code here:
        new Saxophone();
        dispose();
    }//GEN-LAST:event_bttnsaxophoneActionPerformed

    private void bttnprofilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnprofilActionPerformed
        // TODO add your handling code here:
        new Profil();
        dispose();
    }//GEN-LAST:event_bttnprofilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnbass;
    private javax.swing.JButton bttndrum;
    private javax.swing.JButton bttngitar;
    private javax.swing.JButton bttnkeyboard;
    private javax.swing.JButton bttnlogout;
    private javax.swing.JButton bttnprofil;
    private javax.swing.JButton bttnsaxophone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
